<ul>
	<?php
		//取得留言
		$messages = $this->getMessages();
		if(count($messages)>0) :
	?>
		<li>Message History(total: <?php echo count($messages)?>)</li>
		<?php foreach($messages as $message): ?>
			<li>
				<?php echo $message->getName() . ' : ' . $message->getContent(); ?>
			</li>
		<?php endforeach; ?>
	<?php
		else:
	?>
		<li>這裡沒有任何留言</li>
	<?php
		endif;
	?>
</ul>
<br/><br/>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
	<h2 class="legend">留言</h2>
		<ul class="form-list">
			<li>
				<label for="message" class="required"><em>*</em><?php echo $this->__('Message') ?></label>
				<div class="input-box">
					<input type="text" name="message" id="message" value="" title="Message"	class="input-text required-entry" />
				</div>
			</li>
		</ul>
	<div class="buttons-set">
		<button type="submit" title="<?php echo	Mage::helper('core')->quoteEscape($this->__('Submit')) ?>"	class="button">
		<span><span><?php echo $this->__('Submit') ?></span></span></button>
	</div>
</form>
<script type="text/javascript">
	//<![CDATA[
		var dataForm = new VarienForm('form-validate', true);
	//]]>
</script>